title: Ka Blog
tagline: projetos, tutoriais e artigos
description: "portfolio e blog do ka para postar projetos, tutoriais e artigos proprios"
url: ""        # ex: https://seuusuario.github.io
baseurl: "/blog_teste"    # se seu repo for outro nome troca aqui

author:
  name: Ka
  role: arquiteto de experiencias digitais
  email: ""    # opcional

# colecoes (projetos)
collections:
  projects:
    output: true
    permalink: /projetos/:name/

# plugins suportados no github pages (safe)
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

# markdown e sintaxe
markdown: kramdown
kramdown:
  input: GFM

# defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: Ka
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

# build
permalink: /artigos/:categories/:year/:month/:day/:title/
# exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - node_modules
  - vendor
